version: '3.1'

services:
  mysql-db:
    image: mysql:8.0.28
    container_name: mysql-db
    restart: always
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
        MYSQL_ROOT_PASSWORD: password
        MYSQL_DATABASE: seccom-cctv-notifications
        MYSQL_USER: user
        MYSQL_PASSWORD: password
    ports:
        - "9906:3306"
    volumes:
      - seccom-cctv-notifications-mysql-volume:/var/lib/mysql
      
  notifications:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: notifications
    depends_on:
      - mysql-db
    ports:
      - 8082:8080

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    depends_on:
      - mysql-db
    ports:
      - 8000:8080

volumes:
  seccom-cctv-notifications-mysql-volume:
