version: 2.1

jobs:
  test:
    machine: true
    steps:
      - checkout
      - run:
          name: Run Pytest Tests
          command: |
            pip install --upgrade pip
            pip3 install -r requirements.txt
            pytest
            
workflows:
  build-and-test:
    jobs:
      - test
