version: 2.1

orbs:
  python: circleci/python@2.0.3
  aws-ecr: circleci/aws-ecr@8.1.3
jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.10.4
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: |
          pip install -r requirements.txt
          pytest
            
workflows:
  build-and-test:
    jobs:
      - test
      - aws-ecr/build_and_push_image:
          region: us-east-1
          account-url: ${AWS_ECR_ACCOUNT_URL}
          repo: ${CIRCLE_PROJECT_REPONAME}
          tag: ${CIRCLE_BUILD_NUM}